apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - helm-chart.yaml   # ou inline direto

helmCharts:
  - name: uptime-kuma
    repo: https://charts.uptimerobot.com
    version: 1.0.0
    releaseName: uptime-kuma
    namespace: monitoring
    valuesFile: ../config/helm-values.yaml
